#!/usr/bin/env python3
"""
Script de contrôle du générateur de chemin pour la déneigeuse
"""

from deneige.FinalDeneige import solve

# Petit Test
edges = [(2, 1, 5), (1, 2, 1), (1, 0, 2), (0, 3, 1),
         (3, 4, 1), (4, 0, 1), (0, 2, 1)]
s = solve(5, edges)
print(s)
